/*
 SHELL-SORT

 INSERTION SORT IMPROVED
 INSERTION SORT MOVES ONLY ADJACENT ELEMENTS
 SHELL SORT MOVES DISTANT ELEMENTS YAY :P
 ELEMENTS SEPARATED BY H POSITIONS (MULTIPLES OF H), FOR EXAMPLE H = 4

 [H*0]   [1]	[2]	[3]	[H*1]
  10      3      5       2        1

 AFTER SORTING
 [H*0]   [1]	[2]	[3]	[H*1]
   1      3      5       2        10
